vich_uploader:
    db_driver: orm

    mappings:
        projects:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        degrees:
            uri_prefix: /images/degrees
            upload_destination: '%kernel.project_dir%/public/images/degrees'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        works:
            uri_prefix: /images/works
            upload_destination: '%kernel.project_dir%/public/images/works'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        skills:
            uri_prefix: /images/skills
            upload_destination: '%kernel.project_dir%/public/images/skills'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
